local LinearLayoutCompat = bindClass "androidx.appcompat.widget.LinearLayoutCompat"
local CoordinatorLayout = bindClass "androidx.coordinatorlayout.widget.CoordinatorLayout"
local MaterialToolbar = bindClass "com.google.android.material.appbar.MaterialToolbar"
local AppBarLayout = bindClass "com.google.android.material.appbar.AppBarLayout"
local AppCompatImageView = bindClass "androidx.appcompat.widget.AppCompatImageView"
local MaterialCardView = bindClass "com.google.android.material.card.MaterialCardView"
local AppCompatTextView = bindClass "androidx.appcompat.widget.AppCompatTextView"
local MaterialButton = bindClass "com.google.android.material.button.MaterialButton"
local DrawableUtil = require "mods.utils.DrawableUtil"
local TextInputView = require "mods.view.TextInputView"

return {
  CoordinatorLayout,
  w="fill",
  h="fill",
  {
    AppBarLayout,
    backgroundColor=0,
    liftOnScroll=true,
    fitsSystemWindows=true,
    w="fill",
    {
      MaterialToolbar,
      backgroundColor=0,
      layout_scrollFlags=3,
      id="toolbar",
      Title="",
      w="fill",
      h="64dp",
    },
  },
  {
    LinearLayoutCompat,
    w="fill",
    h="fill",
    orientation="vertical",
    paddingBottom="24dp",
    gravity="center",
    layoutTransition=mTransition,
    {
      MaterialCardView,
      StrokeWidth=0,
      radius="360dp",
      CardBackgroundColor="0xFFE0E0E0",
      Alpha=0.3,
      w="70dp",
      h="70dp",
      {
        AppCompatImageView,
        w="fill",
        h="fill",
        ColorFilter=Colors.colorOutline;
        ImageResource=R.drawable.avatar_placeholder
      },
    },
    {
      AppCompatTextView,
      textSize=TextSize + 12,
      Typeface=Typeface_TTF(2),
      text=res.string.login_account,
      id="title",
      layout_marginTop="16dp",
    },
    {
      AppCompatTextView,
      id="content",
      w="fill",
      textSize=TextSize,
      gravity="center",
      Typeface=Typeface_TTF(),
      text=res.string.login_tip,
      layout_margin="16dp",
      layout_marginBottom="8dp",
    },
    {
      TextInputView.TextInputLayout,
      hint=TypefaceString(res.string.account),
      layout_margin="22dp",
      layout_marginTop="14dp",
      layout_marginBottom=0,
      w="fill",
      StartIconDrawable=DrawableUtil("ic_account_outline",Colors.colorOnSurfaceVariant),
      id="textInput_account",
      {
        TextInputView.TextInputEditText,
        id="account",
        singleLine=true,
        w="fill"
      },
    },
    {
      TextInputView.TextInputLayout,
      hint=TypefaceString(res.string.password),
      layout_margin="22dp",
      layout_marginTop="14dp",
      layout_marginBottom=0,
      w="fill",
      StartIconDrawable=DrawableUtil("ic_lock_outline",Colors.colorOnSurfaceVariant),
      EndIconMode=1,
      id="textInput_password",
      {
        TextInputView.TextInputEditText,
        id="password",
        singleLine=true,
        w="fill"
      },
    },
    {
      TextInputView.TextInputLayout,
      hint=TypefaceString(res.string.qq),
      layout_margin="22dp",
      layout_marginTop="14dp",
      layout_marginBottom=0,
      w="fill",
      Visibility=8,
      StartIconDrawable=DrawableUtil("ic_qq",Colors.colorOnSurfaceVariant),
      id="textInput_qq",
      {
        TextInputView.TextInputEditText,
        id="qq",
        singleLine=true,
        w="fill"
      },
    },
    {
      MaterialButton,
      layout_gravity="end",
      layout_margin="22dp",
      text=res.string.login,
      id="login",
      textSize=TextSize,
      Typeface=Typeface_TTF(),
    }
  },
  {
    LinearLayoutCompat,
    layout_gravity="bottom|center",
    layout_margin="16dp",
    gravity="center",
    id="bottom",
    {
      LinearLayoutCompat,
      h="fill",
      layout_weight=1,
      w="50%w",
      gravity="end",
      layoutTransition=mTransition,
      {
        MaterialButton,
        id="forgot",
        style=MDC_R.attr.materialButtonOutlinedStyle,
        StrokeWidth=0,
        textSize=TextSize,
        text=string.lower(res.string.retrieve_password),
        Typeface=Typeface_TTF(),
      },
    },
    {
      MaterialCardView,
      h="fill",
      w="1.5dp",
      radius="360dp",
      layout_margin="16dp",
      StrokeWidth=0,
      Alpha=0.2,
      CardBackgroundColor=Colors.colorOutline,
    },
    {
      LinearLayoutCompat,
      h="fill",
      layout_weight=1,
      w="50%w",
      gravity="left",
      layoutTransition=mTransition,
      {
        MaterialButton,
        id="register",
        style=MDC_R.attr.materialButtonOutlinedStyle,
        StrokeWidth=0,
        textSize=TextSize,
        text=string.lower(res.string.register_account),
        Typeface=Typeface_TTF(),
      },
    },
  },
}
